linux_i2c_test:
	g++-11 -Wall -Wextra -Wpedantic -std=c++20 -o linux_i2c_test linux_i2c_test.cc

duppa_i2c_encoder_mini_test:
	g++-11 -Wall -Wextra -Wpedantic -std=c++20 -o duppa_i2c_encoder_mini_test duppa_i2c_encoder_mini_test.cc

clean:
	rm -f linux_i2c_test
	rm -f duppa_i2c_encoder_mini_test
