# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "objdetect"
version = "0.0.0"
edition = "2021"

[dependencies]
r2r = "0.*"  # requires libclang installed (e.g. libclang-dev on ubuntu)
# futures = "0.*"

[dependencies.pyo3]
version = "0.*"
features = ["auto-initialize"]
